### PR TITLE
Clear shadow warning in initializer

### PR DESCRIPTION
**Pull request by starseeker**

### CODE REVIEW

**Comment by jhasse** [comment]
See #15.

**Comment by jhasse** [comment]
Having shadowing in a header still sucks. Let's keep this open.

**Comment by starseeker** [comment]
Cool - apologies I didn't notice the other issue, I should have posted there...

**Comment by jhasse** [comment]
I've moved the constructor into the .cc file, hopefully this will no longer result in warnings for you :)

**Pull request closed without merging**
